project:
  type: website
  output-dir: docs   # important for GitHub Pages


website:
  title: "Karl-Emil Bendtsen"
  navbar:
    left:
      - href: index.qmd
        text: Home
      # - href: research.qmd
      #   text: Research
      - href: CV_karlemilbendtsen.pdf
        text: CV

format:
  html:
    theme: cosmo
    toc: false
